### PR TITLE
feat: allow to drop files with `transform` option

### PR DESCRIPTION
**Pull request by FezVrasta**
#23

### CODE REVIEW

**Comment by sapphi-red** [comment]
Thank you for the PR! I like this approach.

I think this needs to change around here to support during dev.
https://github.com/sapphi-red/vite-plugin-static-copy/blob/3ff70f2e93467bc5a0d09bbf16993e17d5cab8ac/src/middleware.ts#L168

Also, would you add tests and some docs, too?

**Comment by FezVrasta** [comment]
Should it return a 404?

**Comment by sapphi-red** [comment]
Yes, return 404 and call `next` function if it exists like:
https://github.com/sapphi-red/vite-plugin-static-copy/blob/3ff70f2e93467bc5a0d09bbf16993e17d5cab8ac/src/middleware.ts#L185-L193

**Comment by FezVrasta** [comment]
I'm not sure how to write a test that checks for the file not to be generated, may you help with it?

**Comment by sapphi-red** [comment]
`actual` will be `null` if status code is not 200. So setting `transformedContent: null` in `test/testcases.ts` will work.
https://github.com/sapphi-red/vite-plugin-static-copy/blob/3ff70f2e93467bc5a0d09bbf16993e17d5cab8ac/test/tests.test.ts#L47-L51

**Comment by FezVrasta** [comment]
I get this error
CleanShot 2022-08-24 at 1 28 45@2x

**Comment by sapphi-red** [comment]
Ah, this `null` should be `false` and set `transformedContent: false` instead of `transformedContent: null` to prevent fallback with `??`.
https://github.com/sapphi-red/vite-plugin-static-copy/blob/3ff70f2e93467bc5a0d09bbf16993e17d5cab8ac/test/tests.test.ts#L30

**Comment by FezVrasta** [comment]
CleanShot 2022-08-24 at 1 37 27@2x

:-(

**Comment by sapphi-red** [comment]
Ummm, I think I'm missing something. I'll take a look later.

**Comment by FezVrasta** [comment]
I fixed it by changing `??` with an explicit `undefined` check, hopefully it's okay?

**Comment by sapphi-red** [comment]
Thanks!

I've changed `TransformFunc` to only accpect `null` to be returned.
This is to avoid unintented behavior
```js
const f = (content: string, filename: string) => {
  if (content.includes('foo')) return 'new content'
  // missing `return` here and it will be skipped
  // but it might be not intended
}
```

**Review by sapphi-red — APPROVED** [review]

**Comment by sapphi-red** [comment]
@FezVrasta I have released this as v0.8.0!

**Pull request merged**
