### PR TITLE
feat: add `overwrite` option

### PR DESCRIPTION
**Pull request by jaluik**
Hello, thanks for your great jobs! 

In my case I need copy something and not to overwrite it.  So I hope this vite plugin can expose fs-extra copy options to users. Thanks .

The `fs-extra` copy docs is [here](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/copy.md)

### CODE REVIEW

**Comment by sapphi-red** [comment]
Thanks for the PR!
Would you implement the server part as well to make the behavior consistent? The current behavior will prioritize the copied one instead of the existing one even if the `overwrite: false` is set.
Also would you add a test for this?

**Comment by jaluik** [comment]
ok, I will handle this

**Comment by jaluik** [comment]
I have added the test cases and change the server side logic to make sure that the overwrite config have consistent in vite server and build process  @sapphi-red

**Comment by sapphi-red** [comment]
Thank you! I fixed one bug and refactored a bit. Also I merged `overwrite` and `errorOnExist` into one option as I didn't think we need two options.

**Review by sapphi-red — APPROVED** [review]

**Comment by sapphi-red** [comment]
@jaluik I have released this as v0.15.0!

**Pull request merged**
